### ISSUE TITLE
YouTube thumbnails

### ISSUE THREAD

**Issue by OutshineIssue** [mgriley/BigOlJungle#1]
Thanks for such a cool project, is it possible to add thumbnails to YouTube feeds for easier identification?

**Comment by mgriley** [comment]
Glad you like it! :) Good idea, I'll give it a try. It would be nice to have thumbnails for youtube and favicons for other sites.

**Comment by mgriley** [comment]
I just added thumbnails to the YouTube feeds. Lmk if that helps.

**Comment by OutshineIssue** [comment]
It did! Thanks for adding that so quickly!
